version: '3.8'
services:
  app:
    container_name: docker-react-app
    image: docker-react-i
    
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8080:5000

# version: “3.8”

# services:

#    client:   

#       stdin_open:  true

#       build: 

#           context: .

#           dockerfile: Dockerfile

#       ports:

#           -  3000:8000

      # volumes:

      #     -  “/app/node_modules”

      #     -  “./:/app”

